name: Crystal_Rift
author: Foxxor
description: A sample web application
homepage: https://github.com/foxxor/crystalrift-dart
documentation: https://github.com/foxxor/crystalrift-dart
dependencies:
  browser: any
