name: Crystal_Rift
author: Foxxor
description: An HTML5 2D game engine using dart and canvas.
homepage: https://github.com/foxxor/crystalrift-dart
documentation: https://github.com/foxxor/crystalrift-dart
dependencies:
  browser: any
